-- Subscriptions Table
CREATE TABLE Subscriptions (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    ProductsId UNIQUEIDENTIFIER NOT NULL,
    ApplicationsId UNIQUEIDENTIFIER NOT NULL,
    Version INT NULL,
    Created DATETIME2(7) NOT NULL,
    Changed DATETIME2(7) NOT NULL,
    CreatorId UNIQUEIDENTIFIER NOT NULL,
    ChangedUser UNIQUEIDENTIFIER NOT NULL
);