
CREATE TABLE Applications (
    Id uniqueidentifier NOT NULL PRIMARY KEY,
    Name nvarchar(200) NOT NULL,
    AllowedGrantTypeId uniqueidentifier NOT NULL,
    APICHostname nvarchar(200),
    CredentialsDev nvarchar(max),
    CredentialsProd nvarchar(max),
    Description nvarchar(max),
    IdDev uniqueidentifier,
    IdProd uniqueidentifier,
    EnvironmentId uniqueidentifier NOT NULL,
    ImageId uniqueidentifier,
    Status nvarchar(200),
    ClientIdDev uniqueidentifier,
    ClientIdProd uniqueidentifier,
    ClientSecret nvarchar(max),
    ClientUriDev nvarchar(200),
    ClientUriProd nvarchar(200),
    Version int,
    Created datetime2(7) NOT NULL,
    Changed datetime2(7),
    CreatorId uniqueidentifier NOT NULL,
    ChangedUser uniqueidentifier NOT NULL
);
