CreateTable_ApiTags.sql
CREATE TABLE ApiTags (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Name NVARCHAR(200) NOT NULL,
    Version INT,
    Created DATETIME2(7) NOT NULL,
    Changed DATETIME2(7),
    CreatorId UNIQUEIDENTIFIER NOT NULL,
    ChangedUser UNIQUEIDENTIFIER
);