CreateTable_APIEndpointTags.sql
CREATE TABLE APIEndpointTags (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    APIEndpointId UNIQUEIDENTIFIER NOT NULL,
    APITagId UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (APIEndpointId) REFERENCES APIEndpoints(Id),
    FOREIGN KEY (APITagId) REFERENCES ApiTags(Id)
);