
CREATE TABLE FAQs (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Question NVARCHAR(500) NOT NULL,
    Answer NVARCHAR(MAX) NOT NULL,
    FaqCategoryId UNIQUEIDENTIFIER NULL,
    Langcode NVARCHAR(4) NOT NULL CHECK (Langcode IN ('el', 'en')),
    Status BIT NOT NULL,
    Created DATETIME2(7) NOT NULL,
    Changed DATETIME2(7) NOT NULL,
    Order INT NOT NULL
);
