
CREATE TABLE PhpSdkSettings (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    IDSPortalEnabled NVARCHAR(500) NOT NULL,
    TokenUrl NVARCHAR(500) NOT NULL,
    AuthorizationUrl NVARCHAR(500) NOT NULL UNIQUE,
    UserInfoUrl NVARCHAR(500) NOT NULL,
    PortalUrl NVARCHAR(MAX) NOT NULL,
    ClientId NVARCHAR(500) NOT NULL,
    ClientSecret NVARCHAR(500) NOT NULL,
    GrantType NVARCHAR(500) NOT NULL,
    Scope NVARCHAR(500) NOT NULL,
    HeaderIBMClientId NVARCHAR(500) NOT NULL,
    HeaderIBMClientSecret NVARCHAR(500) NOT NULL,
    IDSConnectLogoutUrl NVARCHAR(500) NOT NULL,
    DisplayApplicationAnalytics NVARCHAR(500) NOT NULL,
    Development NVARCHAR(500) NOT NULL,
    DevelopmentSandboxId NVARCHAR(500) NOT NULL,
    DevelopmentSumAggregatesPerEndpointUrl NVARCHAR(500) NOT NULL,
    DevelopmentSumAggregatesPerEndpointPerDayUrl NVARCHAR(500) NOT NULL,
    DevelopmentScopes NVARCHAR(500) NOT NULL,
    ProductionSumAggregatesPerEndpointUrl NVARCHAR(500) NOT NULL,
    ProductionSumAggregatesPerEndpointPerDayUrl NVARCHAR(500) NOT NULL,
    ProductionScopes NVARCHAR(500) NOT NULL,
    CertificateValidationUrl NVARCHAR(500) NOT NULL,
    Scopes NVARCHAR(500) NOT NULL,
    ProductionCertificateValidationUrl NVARCHAR(500) NOT NULL,
    ReactUrl NVARCHAR(500) NOT NULL,
    DrupalUrl NVARCHAR(500) NOT NULL,
    DrupalUrlAdmin NVARCHAR(500) NOT NULL,
    EmailAddress NVARCHAR(500) NOT NULL,
    MaxAppsPerUser NVARCHAR(500) NOT NULL,
    DisableSnippetGeneration NVARCHAR(500) NOT NULL,
    DisableDocumentationGeneration NVARCHAR(500) NOT NULL,
    JsonApiRoles NVARCHAR(500) NOT NULL UNIQUE
);
